<a href="https://colab.research.google.com/github/VANDANA-ANDE/vandana/blob/master/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.tensor([4], requires_grad=True, dtype=torch.float32)
x

tensor([4.], requires_grad=True)

In [4]:
y = 3 * x**2
y

tensor([48.], grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [8]:
print(x.grad)

tensor([24.])


In [9]:
print(x.grad.item())

24.0


In [10]:
x = torch.tensor([5], dtype=torch.float32)
print(x.requires_grad)

False


In [11]:
x.requires_grad_(True)

tensor([5.], requires_grad=True)

In [12]:
x

tensor([5.], requires_grad=True)

In [15]:
in_layer = torch.tensor([3], requires_grad=True, dtype=torch.float32)
h_layer_2 = in_layer * in_layer
out_layer = torch.log(h_layer_2)

In [16]:
print(in_layer)
print(h_layer_2)
print(out_layer)

tensor([3.], requires_grad=True)
tensor([9.], grad_fn=<MulBackward0>)
tensor([2.1972], grad_fn=<LogBackward>)


In [17]:
out_layer.backward()

In [18]:
print(in_layer.grad)

tensor([0.6667])


In [19]:
x = torch.tensor([2.0], requires_grad=True)
with torch.no_grad(): # context
  y = x**2
  print(x.grad_fn)
  print(y.grad_fn)

None
None
