<a href="https://colab.research.google.com/github/VANDANA-ANDE/vandana/blob/master/Pytorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd : Automatic Differentiation

Pytorch has a package called `autograd` which tracks all the operations that you perform on any tensor and then automatically generates the gradients for that tensor.

In [ ]:
import torch

In [ ]:
x = torch.tensor([4], requires_grad=True, dtype=torch.float32)
x

tensor([4.], requires_grad=True)

Every `Tensor` associated with a `Function`.

When the `.requires_grad` attribute is set to `True`, the `grad_fn` attribute stores a `Function` that gives us the derivative/gradient of each operation on that tensor

Each tensor stores its gradient value with it in a buffer. That buffer can be accessed by the `grad` attribute of that tensor

In [ ]:
y = 3 * x**2
y

tensor([48.], grad_fn=<MulBackward0>)

$y = 3x^2 = 3 \times 4^2  = 3 \times 16 = 48$

$y\prime = 6x = 6 \times 4 = 24$

In [ ]:
y.backward()

In [ ]:
print(x.grad)

tensor([24.])


In [ ]:
print(x.grad.item())

24.0


In [ ]:
x = torch.tensor([5], dtype=torch.float32)
print(x.requires_grad)

False


In [ ]:
x.requires_grad_(True)

tensor([5.], requires_grad=True)

In [ ]:
x

tensor([5.], requires_grad=True)

## Training

In [ ]:
in_layer = torch.tensor([3], requires_grad=True, dtype=torch.float32)
h_layer_2 = in_layer * in_layer
out_layer = torch.log(h_layer_2)

In [ ]:
print(in_layer)
print(h_layer_2)
print(out_layer)

tensor([3.], requires_grad=True)
tensor([9.], grad_fn=<MulBackward0>)
tensor([2.1972], grad_fn=<LogBackward>)


In [ ]:
out_layer.backward()

In [ ]:
print(in_layer.grad)

tensor([0.6667])


## Evaluation

In [ ]:
x = torch.tensor([2.0], requires_grad=True)
with torch.no_grad(): # context
  y = x**2
  print(x.grad_fn)
  print(y.grad_fn)

None
None
